name: Integracion continua

on: 	
  pull_request:
     branches: [ main ]
         
jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Correr pruebas 
        run: mvn test